%% Prepare
% Note: please make BRAS resource files available
% URL: https://depositonce.tu-berlin.de/handle/11303/7506.2

if ~exist( 'IR', 'var' )
    load( 'Genelec8020_DAF_2016_1x1_64442_IR_front_pole.mat' )
end

BRAS_Genelec8020_sampling_rate = 44100;
BRAS_Genelec8020_speed_of_sound = 341.0; % m/s
BRAS_Genelec8020_measurement_distance = 1.8; % m
BRAS_Genelec8020_delay_samples = BRAS_Genelec8020_sampling_rate * BRAS_Genelec8020_measurement_distance / BRAS_Genelec8020_speed_of_sound;

BRAS_Genelec8020_IR_userdata = struct();
BRAS_Genelec8020_IR_userdata.IR = IR;
BRAS_Genelec8020_IR_userdata.Phi = Phi;
BRAS_Genelec8020_IR_userdata.Theta = Theta;
BRAS_Genelec8020_IR_userdata.Peak = max( abs( IR ), [], 'all' );
BRAS_Genelec8020_IR_userdata.Scale = false;
BRAS_Genelec8020_IR_userdata.NormalizeFront = false;

if ~exist( 'MPS', 'var' ) || ~exist( 'Frequency', 'var' )
    load( 'Genelec8020_DAF_2016_1x1_64442_MPS_front_pole.mat' )
end
BRAS_Genelec8020_MPS_userdata = struct();
BRAS_Genelec8020_MPS_userdata.MPS = MPS;
BRAS_Genelec8020_MPS_userdata.Frequency = Frequency;
BRAS_Genelec8020_MPS_userdata.Phi = Phi;
BRAS_Genelec8020_MPS_userdata.Theta = Theta;
BRAS_Genelec8020_MPS_userdata.Peak = max( abs( MPS ), [], 'all' );
BRAS_Genelec8020_MPS_userdata.Scale = false;
BRAS_Genelec8020_MPS_userdata.NormalizeFront = false;

addpath( '../..' ) % Find daffv17_write and daffv17_add_metadata function

% @todo correct!
BRAS_metadata_base = [];
BRAS_metadata_base = daffv17_add_metadata( BRAS_metadata_base, 'Description', 'String', 'BRAS Genelec 8020' );
BRAS_metadata_base = daffv17_add_metadata( BRAS_metadata_base, 'Creation date', 'String', date );
BRAS_metadata_base = daffv17_add_metadata( BRAS_metadata_base, 'License', 'String', 'CC BY-NC 4.0' );
BRAS_metadata_base = daffv17_add_metadata( BRAS_metadata_base, 'CC License Deed', 'String', 'https://creativecommons.org/licenses/by-nc/4.0/' );
BRAS_metadata_base = daffv17_add_metadata( BRAS_metadata_base, 'Generation script', 'String', 'Opendaff-v1.7/matlab/directivities/BRAS/BRAS_Genelec8020.m' );
BRAS_metadata_base = daffv17_add_metadata( BRAS_metadata_base, 'Web Resource (2016)', 'String', 'https://depositonce.tu-berlin.de/handle/11303/7506.2' );
BRAS_metadata_base = daffv17_add_metadata( BRAS_metadata_base, 'measurement_distance', 'Float', BRAS_Genelec8020_measurement_distance );
BRAS_metadata_base = daffv17_add_metadata( BRAS_metadata_base, 'delay_samples', 'Float', BRAS_Genelec8020_delay_samples );


%% Impulse response (untouched)

daffv17_write( 'filename', 'Genelec8020_DAF_2016_1x1.v17.ir.daff', ...
                'datafunc', @df_BRAS_directivity_ir, ...
                'userdata', BRAS_Genelec8020_IR_userdata, ...
                'metadata', BRAS_metadata_base, ...
                'content', 'ir', ...
                'alphares', 1, ...
                'betares', 1, ...
                'orient', [ 0 -90 0 ], ...
                'channels', 1, ...
                'quantization', 'float32' );
            
% Verification
daff_dir = DAFF( 'Genelec8020_DAF_2016_1x1.v17.ir.daff' );

Genelec8020_front_verify = itaAudio( 1 );
Genelec8020_front_verify.timeData( :, 1 ) = daff_dir.nearest_neighbour_record( 0, 0 )';
Genelec8020_front_verify.timeData( :, 2 ) = IR( :, and( Phi == 0, Theta == 0 ) );
Genelec8020_front_verify.channelNames = { 'DAFF frontal direction', 'BRAS frontal direction' };

Genelec8020_back_verify = itaAudio( 1 );
Genelec8020_back_verify.timeData( :, 1 ) = daff_dir.nearest_neighbour_record( 180, 0 )';
Genelec8020_back_verify.timeData( :, 2 ) = IR( :, and( Phi == 0, Theta == 180 ) );
Genelec8020_back_verify.channelNames = { 'DAFF back direction', 'BRAS back direction' };

Genelec8020_ceil_floor_verify = itaAudio( 1 );
Genelec8020_ceil_floor_verify.timeData( :, 1 ) = daff_dir.nearest_neighbour_record( 0, 90 );
Genelec8020_ceil_floor_verify.timeData( :, 2 ) = IR( :, and( Phi == 0, Theta == 90 ) );
Genelec8020_ceil_floor_verify.timeData( :, 3 ) = daff_dir.nearest_neighbour_record( -90, 0 );
Genelec8020_ceil_floor_verify.timeData( :, 4 ) = IR( :, and( Phi == 180, Theta == 90 ) );
Genelec8020_ceil_floor_verify.channelNames = { 'DAFF ceiling direction (reversed normalization)', 'BRAS ceiling direction', ...
                   'DAFF floor direction (reversed normalization)', 'BRAS floor direction' };

c = itaAudio( 1 );
c.timeData( :, 1 ) = daff_dir.nearest_neighbour_record( 90, 0 );
c.timeData( :, 2 ) = IR( :, and( Phi == 90, Theta == 90 ) );
c.timeData( :, 3 ) = daff_dir.nearest_neighbour_record( -90, 0 );
c.timeData( :, 4 ) = IR( :, and( Phi == 270, Theta == 90 ) );
c.channelNames = { 'DAFF left direction', 'BRAS left direction', ...
                   'DAFF right direction', 'BRAS right direction' };

d = itaAudio();
d.timeData( :, 1 ) = daff_dir.nearest_neighbour_record( 135, 45 );
d.timeData( :, 2 ) = IR( :, and( Phi == 45, Theta == 135 ) );
c.channelNames = { 'DAFF rear left elevated direction', 'BRAS rear left elevated direction' };
d.pf

various_directions = ita_merge( Genelec8020_front_verify, Genelec8020_ceil_floor_verify, c, d );
various_directions.pf

prob_channels = ita_merge( Genelec8020_ceil_floor_verify.ch( 3 ), c.ch(4) )

%% Impulse response (scaled by maximum)
BRAS_Genelec8020_IR_userdata.Scale = true;
BRAS_Genelec8020_IR_userdata.NormalizeFront = false;
daffv17_write( 'filename', 'Genelec8020_DAF_2016_1x1_scaled.v17.ir.daff', ...
                'datafunc', @df_BRAS_directivity_ir, ...
                'userdata', BRAS_Genelec8020_IR_userdata, ...
                'metadata', BRAS_metadata_base, ...
                'content', 'ir', ...
                'alphares', 1, ...
                'betares', 1, ...
                'orient', [ 0 -90 0 ], ...
                'channels', 1, ...
                'quantization', 'float32' );

%% Impulse response (normalized to front direction)
BRAS_Genelec8020_IR_userdata.Scale = false;
BRAS_Genelec8020_IR_userdata.NormalizeFront = true;
daffv17_write( 'filename', 'Genelec8020_DAF_2016_1x1_normalized.v17.ir.daff', ...
                'datafunc', @df_BRAS_directivity_ir, ...
                'userdata', BRAS_Genelec8020_IR_userdata, ...
                'metadata', BRAS_metadata_base, ...
                'content', 'ir', ...
                'alphares', 1, ...
                'betares', 1, ...
                'orient', [ 0 -90 0 ], ...
                'channels', 1, ...
                'quantization', 'float32' );
            
%% Impulse response (short, low res, otherwise untouched)
BRAS_Genelec8020_IR_userdata.filter_length = 256;
daffv17_write( 'filename', 'Genelec8020_DAF_2016_5x5_256.v17.ir.daff', ...
                'datafunc', @df_BRAS_directivity_ir, ...
                'userdata', BRAS_Genelec8020_IR_userdata, ...
                'metadata', BRAS_metadata_base, ...
                'content', 'ir', ...
                'alphares', 5, ...
                'betares', 5, ...
                'orient', [ 0 -90 0 ], ...
                'channels', 1, ...
                'quantization', 'float32' );
            

%% Generate & export DFT version
daffv17_write( 'filename', 'Genelec8020_DAF_2016_1x1.v17.dft.daff', ...
                'datafunc', @df_BRAS_directivity_dft, ...
                'userdata', BRAS_Genelec8020_IR_userdata, ...
                'metadata', BRAS_metadata_base, ...
                'content', 'dft', ...
                'alphares', 1, ...
                'betares', 1, ...
                'orient', [ 0 -90 0 ], ...
                'channels', 1, ...
                'quantization', 'float32' );
            
            
%% Magnitude & Phase spectrum

daffv17_write( 'filename', 'Genelec8020_DAF_2016_1x1.v17.mps.daff', ...
                'datafunc', @df_BRAS_directivity_mps, ...
                'userdata', BRAS_Genelec8020_MPS_userdata, ...
                'metadata', BRAS_metadata_base, ...
                'content', 'mps', ...
                'alphares', 1, ...
                'betares', 1, ...
                'orient', [ 0 -90 0 ], ...
                'channels', 1, ...
                'quantization', 'float32' );

daffv17_write( 'filename', 'Genelec8020_DAF_2016_1x1.v17.ms.daff', ...
                'datafunc', @df_BRAS_directivity_ms, ...
                'userdata', BRAS_Genelec8020_MPS_userdata, ...
                'metadata', BRAS_metadata_base, ...
                'content', 'ms', ...
                'alphares', 1, ...
                'betares', 1, ...
                'orient', [ 0 -90 0 ], ...
                'channels', 1, ...
                'quantization', 'float32' );

